version: 2
jobs:
  build:
    working_directory: ~/tell
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Clean
          command: ./gradlew clean
      - run:
          name: Check
          command: ./gradlew check
      - run:
          name: Test
          command: ./gradlew test