version: 2

jobs:
  build:
    working_directory: ~/tell
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Clean
          command: ./gradlew clean
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-settings-{{ checksum "settings.gradle.kts" }}
      - run:
          name: Test
          command: ./gradlew test
      - store_test_results:
          path: build/test-results/test
      - run:
          name: Coverage Report
          command: ./gradlew jacocoTestReport
      - store_artifacts:
          path: build/reports
      - run:
          name: Jar
          command: ./gradlew jar
      - store_artifacts:
          path: build/libs
