version: 2

jobs:
  build:
    working_directory: ~/tell
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Clean
          command: ./gradlew clean
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-settings-{{ checksum "settings.gradle" }}
      - run:
          name: Test
          command: ./gradlew junitPlatformTest
      - store_test_results:
          path: build/test-results/junit-platform
      - run:
          name: Coverage Report
          command: ./gradlew junitPlatformJacocoReport
      - store_artifacts:
          path: build/reports
      - run:
          name: Jar
          command: ./gradlew jar
      - store_artifacts:
          path: build/libs
