version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Clean
          command: ./gradlew clean
      - run:
          name: Check
          command: ./gradlew check
      - run:
          name: Test
          command: ./gradlew test